[package]
name = "web-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# 查看 actix-web 版本: cargo search actix-web
# actix-web = "1.0.8"
actix-web = "4.8.0"
# serde = { version = "1.0", features = ["derive"] }
serde = { version = "1.0.204", features = ["derive"] }
